# Generated by Django 4.1.1 on 2023-04-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tovar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("second_name", models.CharField(max_length=30)),
                ("costs", models.IntegerField(default=0)),
            ],
        ),
    ]
