# Generated by Django 4.1.1 on 2023-04-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_tovar"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
