# Generated by Django 4.1.1 on 2023-05-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_users_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Tovar",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
