# Generated by Django 4.1.1 on 2023-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_contact_delete_tovar_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tovar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("amount", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("made_by", models.CharField(max_length=20)),
            ],
        ),
    ]
