# Generated by Django 4.1.1 on 2023-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_tovar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tovar",
            name="name",
            field=models.CharField(
                error_messages={"required": "Please enter your name."}, max_length=25
            ),
        ),
    ]
