# Generated by Django 4.1.1 on 2023-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_tovar_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tovar",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
