# Generated by Django 4.1.1 on 2023-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_tovar_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.AlterField(
            model_name="tovar",
            name="cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tovar",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
