# Generated by Django 4.1.1 on 2023-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_delete_contact_alter_tovar_cost_alter_tovar_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
