# Generated by Django 4.1.1 on 2023-05-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tovar",
        ),
    ]
