# Generated by Django 4.1.1 on 2023-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_delete_tovar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tovar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("amount", models.IntegerField(default=0)),
                ("cost", models.IntegerField(default=0)),
                ("made_by", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=60)),
            ],
        ),
    ]
